CREATE TABLE IF NOT EXISTS raw_data (
    id INTEGER,
    customer_first_name VARCHAR(255),
    customer_last_name VARCHAR(255),
    customer_age INTEGER,
    customer_email VARCHAR(255),
    customer_country VARCHAR(255),
    customer_postal_code VARCHAR(50),
    customer_pet_type VARCHAR(100),
    customer_pet_name VARCHAR(255),
    customer_pet_breed VARCHAR(255),
    seller_first_name VARCHAR(255),
    seller_last_name VARCHAR(255),
    seller_email VARCHAR(255),
    seller_country VARCHAR(255),
    seller_postal_code VARCHAR(50),
    product_name VARCHAR(255),
    product_category VARCHAR(100),
    product_price DECIMAL(10,2),
    product_quantity INTEGER,
    sale_date VARCHAR(50),
    sale_customer_id INTEGER,
    sale_seller_id INTEGER,
    sale_product_id INTEGER,
    sale_quantity INTEGER,
    sale_total_price DECIMAL(12,2),
    store_name VARCHAR(255),
    store_location VARCHAR(255),
    store_city VARCHAR(255),
    store_state VARCHAR(255),
    store_country VARCHAR(255),
    store_phone VARCHAR(50),
    store_email VARCHAR(255),
    pet_category VARCHAR(100),
    product_weight DECIMAL(10,2),
    product_color VARCHAR(100),
    product_size VARCHAR(50),
    product_brand VARCHAR(255),
    product_material VARCHAR(255),
    product_description TEXT,
    product_rating DECIMAL(3,1),
    product_reviews INTEGER,
    product_release_date VARCHAR(50),
    product_expiry_date VARCHAR(50),
    supplier_name VARCHAR(255),
    supplier_contact VARCHAR(255),
    supplier_email VARCHAR(255),
    supplier_phone VARCHAR(50),
    supplier_address VARCHAR(255),
    supplier_city VARCHAR(255),
    supplier_country VARCHAR(255)
);

COPY raw_data FROM '/data/mock_data_5.csv' WITH (FORMAT csv, HEADER true);
COPY raw_data FROM '/data/mock_data_6.csv' WITH (FORMAT csv, HEADER true);
COPY raw_data FROM '/data/mock_data_7.csv' WITH (FORMAT csv, HEADER true);
COPY raw_data FROM '/data/mock_data_8.csv' WITH (FORMAT csv, HEADER true);
COPY raw_data FROM '/data/mock_data_9.csv' WITH (FORMAT csv, HEADER true);
